# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8bebeb7e0712aa610c59ba69e5ee657771455d42d600001136af823b2b7c6ab738ba9368749e758ccbe5998222ff2459819d3ad62d34cd44a38dd8b42999c45

test:
  secret_key_base: f87739e1610cda2e71a29410d31c5c0ecd17b45dd3d326dce45e82aea395705bb8e4ca52238d9654f0c2986b131d4520919958657b2c04ec30f9bf7b21197595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
